name: Privado Scan
on: push
    
jobs:
  privado:
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    env:
      PRIVADO_API_TOKEN: "api84735becd1f3527384e0f5cbcd05ffb46495d1cdc2dc6b0d08"
      PRIVADO_API_ID: "32BF0CD1BE19DF24B761C6FE"
      PRIVADO_API_HOST: "https://audit.gcp.privado-dev.com"
      PRIVADO_CI_PLATFORM: "GITHUB_ACTIONS"
      PRIVADO_DOCKER_IMAGE: 638117407428.dkr.ecr.ap-south-1.amazonaws.com/scanner-agent:latest
      PRIVADO_REPOSITORY_ID: ${{ github.repository_id }}
      PRIVADO_REPOSITORY_NAME: ${{ github.repository }}
      PRIVADO_COMMIT_ID: ${{ github.sha }}
      PRIVADO_BRANCH_NAME: ${{ github.ref_name }}
      PRIVADO_DEFAULT_BRANCH_NAME: ${{ github.event.repository.default_branch }}
      PRIVADO_REPOSITORY_URL: ${{ github.repositoryUrl }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Login to docker registry"
      run: |
        echo "eyJwYXlsb2FkIjoiejBNTHBpVlpFZ0dVWkFQTUNvVGhWakJlSm1FS2s1aWVaZlV6VTc4bmxWOVA1NFMwNHBDdFdsaDI5S01Ed0NRMTVwRzZ5YnZEdjRTMlh0V0lRSGRHNjJoQnB2MmJFdE5ibmc3SXdPWllwLzFYdWFVUnZFSDQyZjRyRlF2T29VMURVYVZ6dTBlcXdzZ0hxMHN4Vm14b1RucFFxcTYwRjI5cFVqOUo3cEJ2MFY5QjVxTFh2eUZsSThGNWZpdjc0cW4ySmtTNkh4UlNoTUdRakpZU1hWb0JOUUU1T2tGUlNvUjhEeGs4Yzl0SkZpdEMvd3FLVDVHNHBVeVQydjFGKzgycDR2UVY4TnB3eEFHQ2ZETUQyVGYwdVh4aThJV21jRVBqd2FGZFU2UFcxTW5XcXdDREliUWlIeDBTVnFUWHZvTHZNbXNHbm5ocFplVHp1WjF2M3BXOHQ5SU9ORmx3TmxnWmI0ZHROdWJwMGRuVWY1cUZnb3E3am9SMlhSL24zVlNHejdzbk90aVFqZ2h5NnVkYUk2ZG5MNVZTVXUvOFkwQTRzTFM3MkdaYWpBNTdLa1lmbDRDREVHR2FDUHNwcVNnZXhBbU8vVS8yTnRvVys1MThsZVZoSW5xWUs0MlJZQjhQQStxS3IwYXRzek9TK1Y5WmVicmFYUDE0dGozSE40am54VnVTZUtTRC9kMDJUZjV1TEZzY1dkSXFNOHNDR25CWGlycWJJWVljdXRPY255SldVdGNBcm9aWWI1TmloV2p6OFM4SXBxVGNaWHZiRzBWLys1b3BiT0JjMU54bDhtcTR5QmptOEQ4SFdxMFA1ZWVsS0J5cnFtWmV3b3VsK0RzdlRuMjVGZVMxeW1MK1lFWURUNjFaUUlETHpxSjZxWU5SQXJ3V2JCV1VIQktXa2dkRjRaVDI2amhkWlMvamNJMitZN1c1Qnc0bm1EMTJrL2J6eS9WR3kyZXNzY3ZFNnBRM3V5V3V4Q01OQ1VIZC9RQ0R0SXd1VVByQVFteXM1Q1dlcFdBcDV2aXVSenhlUFZKY0R6U1RBSGlhcFRweUUrMk11SW4zYVk1UWlveDBRTVdLWHkrZnl5ZktxdHhWZmRuSDRzeFJQQXo5OXJ4M3VSOGl1djU3TzZIVjFoYXpFMEhrOWNDbXdrQnpTVVBhaEtnWmlBUTFFVjQ1V1huOW5RM2ZRbkI5cVRMV3MyS3hpSjJCbFJXQzROZUMrZVUyYTN0MjkwQlRLWUhzV0ZQSC92aFozQURWMHo5MGhEcThPREVwSnJiYUsxUDh4b2pJeTFkaVQwdFNiMnI4Q01mNkZ0SEpIWkJZVk1SaGd2WnFRV0p6bDZDVlpuM1VsaXBMeXpuQlN6RkpuVGlkQ2tXMVNMQmtuZz09IiwiZGF0YWtleSI6IkFRSUJBSGlIV2FZVG5SVVdDYm56KzdMdk1HK0FQdlRIekhsQlVROUZxRW1WMjZCZHd3RzRjU2EwU2dxdlJTc0NmOUpHV3QzcUFBQUFmakI4QmdrcWhraUc5dzBCQndhZ2J6QnRBZ0VBTUdnR0NTcUdTSWIzRFFFSEFUQWVCZ2xnaGtnQlpRTUVBUzR3RVFRTXBrVEt2YXV0cjRLc0dPTm9BZ0VRZ0R1QUVlOFhGcWxOUUZXL1JPYlBaYTc5cEE0anJrMXNPWnpqVVloTmlzN1lCYlNQZmdYd3h1bkVDcmZOZktqRkhvM1RFbGZkYTc3Sis4TGRuUT09IiwidmVyc2lvbiI6IjIiLCJ0eXBlIjoiREFUQV9LRVkiLCJleHBpcmF0aW9uIjoxNzYxNTgzMzYwfQ==" | docker login --username AWS --password-stdin $PRIVADO_DOCKER_IMAGE
    - name: Run Privado Scanner
      run: |
        env | grep "PRIVADO_" > $GITHUB_WORKSPACE/.privado.env
        docker run -t -v $GITHUB_WORKSPACE:/privado --env-file $GITHUB_WORKSPACE/.privado.env --privileged --pull=always $PRIVADO_DOCKER_IMAGE
